spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      fetch-max-wait: 50
      fetch-min-size: 1048576
      max-poll-records: 100
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: "*"
        allow.auto.create.topic: false
    listener:
      concurrency: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      compression-type: none
      retries: 1
      properties:
        batch-size: 16384
        linger-ms: 0
        max-in-flight-requests-per-connection: 3
        enable-idempotence: true
